EGF_CONVERGENCE_THRESHOLD = 0.7
EGF_MIN_VIABLE_CLAIMS = 1
EVIDENCE_MASS_CAP = 1.0
CONTRADICTION_DRAG_CAP = 1.0
UNCERTAINTY_RADIUS_MAX = 1.0

SOFTMAX_TRUTHFULNESS_WEIGHT = 1.8
SOFTMAX_ACCURACY_WEIGHT = 1.6
SOFTMAX_COHERENCE_WEIGHT = 1.1
SOFTMAX_UNCERTAINTY_PENALTY_WEIGHT = 1.2
SOFTMAX_FRAGILITY_PENALTY_WEIGHT = 1.0
SOFTMAX_ETHICAL_BONUS = 0.1
SOFTMAX_ETHICAL_PENALTY = -1.0

CACHE_ARTICULATION_TTL = 300
CACHE_RETRIEVAL_TTL = 120
CACHE_FRAGMENT_TTL = 600

MAX_PRIOR_DECISIONS_IN_CONTEXT = 10
MAX_CASES_IN_RETRIEVAL = 10
MAX_PATTERNS_IN_RETRIEVAL = 10

TRIBUNAL_PERMIT_REQUIRES = ["KANT", "LOCKE"]
TRIBUNAL_PERMIT_ANY_OF = ["HUME", "SPINOZA"]
